/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "xqaxhfdijrrsdvbtshqz"
export const supabaseUrl = "https://xqaxhfdijrrsdvbtshqz.supabase.co"
export const publicAnonKey = "sb_publishable_T2Z3sGteL0Ujx7uEgq0C7g_8Y_HWTcI"
export const anonJwt = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxYXhoZmRpanJyc2R2YnRzaHF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM3MDQwMzEsImV4cCI6MjA4OTI4MDAzMX0.AFSMLhO8sf1JNmJm0O3EPeYV83ddQGR65SLWtloJLNg"